### ISSUE TITLE
Error import komponen UserAccount (Unknown custom element: <UserAccount> - did you register the component correctly? For recursive components, make sure to provide the "name" option.)

### ISSUE THREAD

**Issue by ryfazrin** [hendri2212/konseling#1]
Error ketika import komponen UserAccount ke dalam komponen TheHeader. 
Komponen TheHeader terletak di dalam Componen TheContainer.

source code :
Import komponen UserAccount di TheHeader [disini](https://github.com/hendri2212/konseling/blob/eb41eb7e7333f086a269b8f8091276177fd486c3/frontend/src/containers/TheHeader.vue#L17)
Komponen UserAccount [disini](https://github.com/hendri2212/konseling/blob/master/frontend/src/containers/UserAccount.vue)

**Pesan eror di console :**
```vue
`vue.esm.js?4b29:628 [Vue warn]: Unknown custom element: <UserAccount> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <TheHeader>
       <CWrapper>
         <TheContainer> at src/containers/TheContainer.vue
           <App> at src/App.vue
             <Root>
`

**Comment by hendri2212** [comment]
has this been solved
